version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/react-ghas"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "deps"
      include: "scope"
    allow:
      - dependency-type: "all"
    labels:
      - "dependencies"